### ISSUE TITLE
Bruker import broken on nmrium.org

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1022]
Apparently, zipped Bruker data import is broken on nmrium.org, the display simply resets itself. Tested files are attached. Both files work on the cdn instance.
[eugenol_97-53-0.zip](https://github.com/cheminfo/nmrium/files/6427089/eugenol_97-53-0.zip)
[13a_o-toluidin_95-53-4_rohdaten.zip](https://github.com/cheminfo/nmrium/files/6427090/13a_o-toluidin_95-53-4_rohdaten.zip)

**Comment by targos** [comment]
The CDN instance is on an older version. I can reproduce this bug on the dev version too.

**Comment by lpatiny** [comment]
It is related to the presence of the molfile in the zip. If you remove it it is imported. However you don't have processed 2D data I think and therefore it will only display the 1D.

We are refactoring the project so that all the parsing (jcamp, jeol, nmredata, bruker) will be done in the project nmr-parser that could be reused as well in other projects.

**Comment by lpatiny** [comment]
It works now on dev.nmrium.org (but molfile is not yet parsed).

**Comment by jobo322** [comment]
it works and it parses the mol too. [0aa42b1](https://github.com/cheminfo/nmrium/commit/0aa42b1d492f518f77c944f64585899ab00cee60)
