### ISSUE TITLE
Cannot open on Chromium

### ISSUE THREAD

**Issue by bjonnh** [cheminfo/nmrium#1033]
Trying to open the website on chromium I get a blank screen with the menus and a message:
"The NMRium component cannot be displayed on a touch device"

**Comment by lpatiny** [comment]
I don't think it is related to Chromium because it works on my mac.

Do you have a touch screen on your computer ? Do you also have a mouse ?

![image](https://user-images.githubusercontent.com/1484241/117614083-16abb900-b168-11eb-881c-9a5fcd70095d.png)

@targos could you try on your touch screen laptop if it works ?

**Comment by bjonnh** [comment]
I couldn't find what module was displaying this message (or is charged to hide it)

**Comment by targos** [comment]
It works as expected on my touch screen laptop.

**Comment by bjonnh** [comment]
With Chromium:
````json
{
  "pointerFine": false,
  "pointerCoarse": false,
  "pointerNone": true,
  "anyPointerFine": false,
  "anyPointerCoarse": false,
  "anyPointerNone": true,
  "hoverNone": true,
  "hoverHover": false,
  "anyHoverNone": true,
  "anyHoverHover": false
}
````

With Firefox (dev edition)

````json
{
  "pointerFine": true,
  "pointerCoarse": false,
  "pointerNone": false,
  "anyPointerFine": true,
  "anyPointerCoarse": false,
  "anyPointerNone": false,
  "hoverNone": false,
  "hoverHover": true,
  "anyHoverNone": false,
  "anyHoverHover": true
}
````

**Comment by bjonnh** [comment]
Chromium has no extensions and it is a fresh profile.

**Comment by bjonnh** [comment]
I confirm, this works now, thanks!
