### ISSUE TITLE
projection for (H,X) HSQC and (H,H) NOESY with wrong scale

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmrium#1041]
If I use the hsqc and hmbc from nmr-dataset1 (140-67-0), and I skip the 13c from the data group, then, once I try to produce the 1D projection in C-13, the signals are there but they are kind of compressed

![Hamed_110521_Teaching1](https://user-images.githubusercontent.com/47237343/117841734-91b2c380-b27d-11eb-96b6-44c3012f90e4.PNG)

**Comment by nes-cgn** [comment]
The same appears if you use a NOESY - the 1D projection is compressed, too

![Hamed_110521_Teaching2](https://user-images.githubusercontent.com/47237343/117862244-bb2a1a00-b292-11eb-93da-d82077840a47.PNG)

**Comment by hamed-musallam** [comment]
@lpatiny 
it's related to the same thing that you solved before, the domain ( that I get from min, and max), maybe you need to check it again.

**Comment by lpatiny** [comment]
Because it is a projection I would rather say that it is at the level of NMRium. @jobo322 in order to reproduce this please load the following link

https://dev.nmrium.org/?sampleURL=https%3A//cheminfo.github.io/nmr-dataset1/data/2D-140-67-0.json#/

Then create the 13C trace using the following icon:

![image](https://user-images.githubusercontent.com/1484241/118104828-ee2bf500-b3db-11eb-9f43-eb8c4fb8f9a2.png)

We are expected to extract the from / to from the 2D and it seems there is a bug in NMRium at this level. @jobo322  could you have a look and discuss with @hamed-musallam about this ?

**Comment by jobo322** [comment]
I found that the number of points of the projection was wrong. But I also found that the app crash when you try to zoom in Y  by scrolling on the projections.
