### ISSUE TITLE
Integral (re-)calculation by H sum should be optional

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1061]
Currently, all integrals are recalculated based on a H sum when changes are made, e. g. to the range class. For users dealing with mixtures, this behaviour may be unwanted. There should be the option to give a fixed integral value that does not change automatically.

**Comment by lpatiny** [comment]
In the integral and the range panel we would need a toggle icon in the bar

![image](https://user-images.githubusercontent.com/1484241/118511019-ce753380-b731-11eb-8834-036bba198441.png)

When this toggle icon is active (default behaviour) it should be the current behaviour. Meaning that if we remove a line in the table of we change the kind we keep the sum constant.

If this toggle button is not active we don't keep this sum constant but we change it to reflect the changes.  If we change manually a value in the table (click twice on an integral and set the value) it would make sense to change this toggle button so that this value does not change anymore.

Not sure it is the best icon but we could use something like https://fontawesome.com/v4.7.0/icon/link

**Comment by lpatiny** [comment]
I change integral value or I change the sum: Toggle button has no impact.

In case we delete a signal or change the kind, we need depending the toggle button either recalculate or change the sum.

**Comment by jliermann** [comment]
Sorry to re-open the issue, but the logic is wrong. If "constant sum" is on, one would expect that integrals are recalculated if you remove or add ranges. So I suggest to:
- either swap the toggle behaviour ("on" means integral recalculation based on constant sum, "off" means constant relative integral values)
- or change the label of the toggle "fix integral values"
