### ISSUE TITLE
local debugging of dependencies does not work with vite

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#1064]
Before, I had able to check the change of some part of the code of a dependency using the 'npm link' then 'npm start' then the changes would be watched. It does not happen now with vitejs. Could you let me know what I need to set up?

**Comment by jobo322** [comment]
@hamed-musallam @lpatiny  could you help me with this?

**Comment by lpatiny** [comment]
@targos Do you think this is possible ?

**Comment by lpatiny** [comment]
Actually it seems that it is not only in 'watch' mode.

Alejandro edit the npm linked package and he can see the changes in the node_modules folder. However starting vitejs will apparently keep a cached version.

**Comment by targos** [comment]
It seems to work fine on my computer. I did:

```
cd nmr-processing
npm link
cd ../nmrium
npm link nmr-processing
npm run dev
```

And changes to nmr-processing are watched.

**Comment by lpatiny** [comment]
@targos You are completely right. Doing this exact sequence of instructions works correctly.

However if I do
```
cd nmr-processing
npm link
cd ../nmrium
npm run dev
npm link nmr-processing
npm run dev
```
It does not work anymore (meaning it is not the linked package that is taken into account). When you start the first time `npm run dev` (before linking the package) `vite` adds `node/modules/.vite/nmr-processing` cache apparently. Even if you remove `.vite/nmr-processing*` it will still not link the package like if this library was already wrapped in some other cache. However removing the full folder 'node_modules/.vite/ allows `vite` to use the linked package again.

@targos 
- Could you reproduce this ?
- What do you think ? Is this a bug or the expected behaviour ?

**Comment by targos** [comment]
- yes, I can reproduce
- I don't know

**Comment by lpatiny** [comment]
I opened a discussion on `vite` https://github.com/vitejs/vite/discussions/3454

**Comment by lpatiny** [comment]
Here is the answer
```
To always recreate the cached files, you can start the dev server with --force or set server.force to true.

However, it looks like what you want to do in your case is add your package to optimizeDeps.exclude, which will prevent it from being bundled during pre-optimization entirely. This way you won't need to turn off the caching for other things.
```

So here is the link to the option that we need to setup to prevent optimization: https://vitejs.dev/config/#optimizedeps-exclude

**Comment by targos** [comment]
You can also start the dev script with `--force` like this when you work with a linked dependency:

```
npm run dev -- --force
```
