### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1107]
Searching the code for '^let' (using regexp). we see that a lot of variables are defined globally instead of `useRef`.

https://github.com/cheminfo/nmrium/blob/b360911047fb9885a077863b86d882536f775382/src/component/EventsTrackers/BrushTracker.jsx#L21-L21
https://github.com/cheminfo/nmrium/blob/b360911047fb9885a077863b86d882536f775382/src/component/reducer/actions/ZonesActions.ts#L33-L34
https://github.com/cheminfo/nmrium/blob/b360911047fb9885a077863b86d882536f775382/src/component/elements/accordion/AccordionItem.jsx#L3-L3

And there are some more.

**Comment by hamed-musallam** [comment]
@lpatiny 
yes, we can use useRef, these lines were written at the beginning of the progject when I thought we have only one instance of the nmrium. I will try to look for all these variables and convert it to the local variable using useRef if it belongs to react component otherwise that I have to store it inside the global state.

**Comment by hamed-musallam** [comment]
@lpatiny 
done, link to d7af1f6e9b0d6f41debfc74dbe3fe0cfb004ffac and dab166555fb9eb7459aaaba7ee162d6ab402ca97.
What left is the Input Range component that you working on it right now.
