### ISSUE TITLE
nullish coalescing operator  problem when import v13 or higher

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1119]
@targos 
Is it a problem when compile and build nmurim?

**Comment by hamed-musallam** [comment]
When we import nmrium in another project.

في الجمعة، ١١ يونيو ٢٠٢١ ٣:٤٤ م Michaël Zasso ***@***.***>
كتب:

**Comment by hamed-musallam** [comment]
@targos 
When we import nmrium in another project.

**Comment by targos** [comment]
I'll need more information about the kind of project, what is used to bundle it, on what platform you execute it...

**Comment by michaelwenk** [comment]
@targos Hamed and me were talking about that because when I try to use nmrium with version 0.13 or higher in our project then following error appears:
<img width="1029" alt="Bildschirmfoto 2021-07-14 um 13 37 17" src="https://user-images.githubusercontent.com/30418272/125615990-760cc54d-5dc1-42b6-808a-2ba1d42f9ad6.png">
 Last working version for us is 0.12.

Here is the link to the project with all the settings: [https://github.com/michaelwenk/webcase-frontend](url)

**Comment by targos** [comment]
I removed the operator in https://github.com/cheminfo/nmrium/commit/150372717efe684efe715dfcfec51235b3a70b85 but this is ultimately an issue with create-react-app.

**Comment by hamed-musallam** [comment]
@targos 

he can just downgrade Chrom to version 79  

https://github.com/ComPlat/nmr_displayer/pull/6/commits/c7d89f1518a5a7dece7dba1d7393820d8a895466

**Comment by michaelwenk** [comment]
@hamed-musallam @targos Thank you very much! It works now with version 0.17.0
