### ISSUE TITLE
JResolv example

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1152]
Do we have a testcase of Jresolv on dev.nmrium.org ?

**Comment by jobo322** [comment]
There is not a testcase for Jresolv, we need to be able to changes some options in the xyzAutoPeakPicking in order to get good results in jres spectra or to have a wrapper of this function that for each kind of spectra execute a particular procedure, I was thinking in the last option to implement it in nmr-global-peakpicking package but the first one would not fall bad

**Comment by jobo322** [comment]
I did add one spectrum to [nmr-dataset-demo](https://github.com/cheminfo/nmr-dataset-demo)
