### ISSUE TITLE
Resolve TODOs about d3-path

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#1351]
There are a few TODOs that are all about the same thing.

We should build the svg paths using d3 instead of manual string construction.

https://github.com/d3/d3-path/blob/main/README.md#path (no need to add a new dependency, the methods should be available in the `d3` package)

For example:
https://github.com/cheminfo/nmrium/blob/efe0f0a4b4f94df2535fc51390956f5320db840b/src/component/1d/Line.tsx#L46-L57

**Comment by lpatiny** [comment]
@targos Just wondering if d3 is the best implementation (anyway this reduce is not ok neither). 

https://github.com/d3/d3-path/blob/main/src/path.js

It seems to me that d3 creates huge amount of intermediate path strings. I would rather use the old array join trick.

Please take care that the current code is rather tricky because you slice pathPoints.x but not point.y (and therefore you have this weird `y[i + 1]`

So I propose the following kind of code (didn't test it) that doesn't slice (waste of time / memory) and doesn't create intermediate strings.

```js
let path = [];
path.push(`M ${_scaleX(pathPoints.x[0])} ${_scaleY(pathPoints.y[0])} `);
for (let i=1; i<pathPoints.x.length; i++) {
  path.push(`L ${_scaleX(pathPoints.x[i])} ${_scaleY(pathPoints.y[i])} `);
}
return path.join(' ');
```

Reference: https://jsbench.me/fxkll021qz

**Comment by targos** [comment]
@lpatiny I'm fine with not using d3-path, but I would like to have a similar internal API to simplify the code.
Something like:

```js
const pathBuilder = new PathBuilder(); // internally create the array
pathBuilder.moveTo(_scaleX(pathPoints.x[0]), _scaleY(pathPoints.y[0])); // internally push a M instruction to the array
for (let i=1; i<pathPoints.x.length; i++) {
  pathBuilder.lineTo(_scaleX(pathPoints.x[i]), _scaleY(pathPoints.y[i])); // internally push a L instruction to the array
}
return pathBuilder.toString(); // internally return array.join(' ')
```

What do you think?

**Comment by lpatiny** [comment]
For me both are readable and should give the same performance so I have no preferences.

**Comment by targos** [comment]
Reopening because of https://github.com/cheminfo/nmrium/pull/1358#pullrequestreview-868046029
