### ISSUE TITLE
Error in 1D ranges

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmrium#1465]
When I want to mark areas manually, NMRium crashes. I do this: click on the "Ranges picking" button, click on the Shift key and move the mouse over the corresponding signal. When I then drop the left mouse button, the program crashes. I can repeat it with several spectra. If you don't understand what I mean, I can gladly record a video.

**Comment by hamed-musallam** [comment]
@evaziegler 
can you record a video so we can be sure of the case?

**Comment by evaziegler** [comment]
Of course. I will send it in a few minutes.

________________________________
Von: hamed-musallam ***@***.***>
Gesendet: Dienstag, 5. April 2022 13:58:45
An: cheminfo/nmrium
Cc: Ziegler, Dr. Eva; Mention
Betreff: Re: [cheminfo/nmrium] Error in 1D ranges (Issue #1465)


@evaziegler<https://github.com/evaziegler>
can you record a video so we can be sure of the case?

**Comment by evaziegler** [comment]
[Error ranges picking.zip](https://github.com/cheminfo/nmrium/files/8418061/Error.ranges.picking.zip)

**Comment by lpatiny** [comment]
@evaziegler I can not reproduce this problem with indometacin. Could you zip and upload the jcamp file of your spectrum ? The multiplicity is quite complex and this could be related to the crash.

Could you also try on https://dev.nmrium.org ? To be certain that the bug is still present.

Also please open the error message if it appears on https://dev.nmrium.org and also paste the message in this issue.

**Comment by jliermann** [comment]
I tried it myself and the crash happens when you use an FID and do the FFT on it. Manual ranges picking leads to a crash every time.

If you use processed 1D files it does not crash.

I attached the console output from Firefox.
[console-export-2022-4-21_17-12-14.txt](https://github.com/cheminfo/nmrium/files/8532248/console-export-2022-4-21_17-12-14.txt)
.

**Comment by jliermann** [comment]
Steps to reproduce:
- Load any FID file (e.g., the attached one)
- Do FFT and automatic phase correction
- Zoom in
- Do manual ranges picking

[1.zip](https://github.com/cheminfo/nmrium/files/8532270/1.zip)

**Comment by hamed-musallam** [comment]
@jliermann 
can you test it and report if the bug still exists.
