### ISSUE TITLE
Autoassignment not working

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1478]
Neither ethyl vinyl ether and neither ethyl benzene are working correctly.

Not all the protons are actually assigned. Quite strange, it seems to me it was working better before.

This is the case on https://dev.nmrium.org

@jobo322 could you have a look ? What is the problem ?

**Comment by jobo322** [comment]
I got it for ethyl-benzene 

![image](https://user-images.githubusercontent.com/12143935/163673655-c1a5e199-cb82-4fd3-bc55-c55575f58476.png)

seems that exist a error in nmrium in the highlight, I did report this, let see if with this  the issue is over.

![image](https://user-images.githubusercontent.com/12143935/163673674-16894f32-01d5-4725-89b4-bf7b231a6882.png)

the correct assignment seems to be in the `diaIDs` property.
