### ISSUE TITLE
Spectrum setting modal take time to be rendered

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1517]
when clicking on the spectrum setting, the modal is take time to be visible, I think it is related to the histogram, maybe react plot takes time to be rendered

![image](https://user-images.githubusercontent.com/35760236/165499793-79b25580-13da-42dc-9534-217bb811414b.png)

![image](https://user-images.githubusercontent.com/35760236/165499469-5edc1989-d251-4789-8c04-55dac57ab72c.png)

**Comment by hamed-musallam** [comment]
@lpatiny what do you think we have to do? do we have to reduce the data that we pass to react plot?

**Comment by lpatiny** [comment]
This is weird because if you test locally (using `npm start`) it is much faster. I would say 10 times faster in development mode than in production mode.

Also it seems that in production (https://dev.nmrium.org) we have many times the calculation of the scatter plot.

![image](https://user-images.githubusercontent.com/1484241/165505093-c07eb399-9290-4e6c-bed6-49106f04173d.png)

@hamed-musallam Could you confirm that in develoement mode it is faster ?

**Comment by hamed-musallam** [comment]
@lpatiny 

it is not obvious to me, I can not see performance differences between the development mode and the production mode

**Comment by lpatiny** [comment]
@hamed-musallam

Could you add a storybook in https://github.com/zakodium-oss/react-plot so that we can try to improve the performances ?

**Comment by hamed-musallam** [comment]
@lpatiny 

i created a PR https://github.com/zakodium-oss/react-plot/pull/399, https://deploy-preview-399--react-plot.netlify.app/?path=/story/sanplot--san-plot-example

**Comment by targos** [comment]
The performance issue is fixed in react-plot@0.18.0
