### ISSUE TITLE
Specify the initial width of the side panel in percentage

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1558]
https://github.com/NFDI4Chem/nmrium-react-wrapper/issues/24

**Comment by lpatiny** [comment]
I think we should allow either a '%' or just a number represented as a string '123' if we want to defined the width of the side panel in pixels.

the '20%' or '120' if the approach we are using in react-plot. (Number type being reserved for values in the units of the axes).

**Comment by targos** [comment]
I'd like to discuss this with you Luc

**Comment by targos** [comment]
@hamed-musallam no need to revert.

**Comment by lpatiny** [comment]
It seems that practically the size in '%' does not make sense. Screen sizes are too diverse and practically it is never ok.

The size that is currently fixed was selected in order to have the minimal width of the panels that is useable. Under this value it becomes useless.

This is why we should rather hide the panels if the size is too small as long as the user didn't modify this manually. This problem will partially be solve in the future when we will be able to store the state containing the layout.

For now it seems that the best behaviour would be to hide dynamically the panel if the size is not bit enough

@hamed-musallam could you have a look at

https://github.com/zakodium-oss/analysis-ui-components/issues/143
