### ISSUE TITLE
Ignoring of wobble curve does not work for this spectrum

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1581]
Hi everybody,

@evaziegler found this spectrum were the wobble curve is still loaded although that should not happen since #763 was closed. I wonder what's different here?

[2-picolin_109-06-8_1H.zip](https://github.com/cheminfo/nmrium/files/8870394/2-picolin_109-06-8_1H.zip)

**Comment by jobo322** [comment]
@jliermann @lpatiny seems we could not be sure about `##$SPECTYP` property because for the current case, the experiment is `proton` . I found that topspin save the  wobble curves  with procno 700 + number of atma attempt. So If you are agree we could ignore procno >= 700 as a option (true by default) in `brukerconverter`

**Comment by lpatiny** [comment]
I'm not fan of hardcoded values.

By default I would rather keep only the first 'pdata'. In this case '1'. I'm surprised that currently we keep all of them.

@jobo322 could you add an option in brukerconverter: `onlyFirstProcessedData` that is `false` by default (in brukerconverter package).

**Comment by jliermann** [comment]
Hi @jobo322 @lpatiny 
I think Luc's idea is very good. There will hardly be any cases where you need more than 1 procno in nmrium.

**Comment by jliermann** [comment]
Thanks for fixing! :)
