### ISSUE TITLE
Problematic bruker file

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1764]
This issue was raised by Michel Gravel

The artifact is caused by the data acquisition mode (AQ_mod parameter for Bruker). For up-to-date NMR instruments (FBR1 and SSSC600, for our case), DQD is usually used. But for old instruments, DQD can't be used when the spectral width is too broad. Qsim will be used, instead. For FBR2, the maximum spectral width to be able to use DQD is 25 kHz (198.71 ppm). This will be problematic for some compounds with signals covering more than 200 ppm."
He was able to solve the problem by modifying the acquisition parameters. However, it does not eliminate that artifact for FID that were acquired prior to this problem being noticed. Are you aware if others have experienced that problem? If so, do you have a solution so that older FID could be processed without displaying this artifact? I am not sure why, but this artifact does not appear in Topspin. So it looks like Topspin is able to remove it somehow or perhaps there is a file in the zipped folder that deals with the problem for Topspin but not for nmrium.

[rgk-dialdehydecarbon.zip](https://github.com/cheminfo/nmrium/files/9622759/rgk-dialdehydecarbon.zip)

**Comment by lpatiny** [comment]
Here is what we currently obtain:

![image](https://user-images.githubusercontent.com/1484241/191672911-1c592fbd-32a7-4609-9578-1e392654a885.png)

**Comment by jobo322** [comment]
I catch the problem with this FID. it is not centered in zero. @lpatiny do you know if exists more samples with the same problem? would be nice to check if my fixing works for all of those samples.

![image](https://user-images.githubusercontent.com/12143935/192791837-80c7241c-ffea-4f67-b403-5590336047fc.png)

it is the result of topspin

![image](https://user-images.githubusercontent.com/12143935/192792081-0fd3f2e8-4de7-462d-af10-35abe5cd2d7a.png)

there is still an artifact but I think we are on the right way.

The idea is to center the FID before FFT, in order to keep the original FID. @lpatiny what do you think?
