### ISSUE TITLE
Phase correction crash after absolute

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1766]
If you make a FT and phase correction 'absolute' then going back at the level of the ft filter and reapply a phase correction NMRium crash.

![2022-09-22 11 16 13](https://user-images.githubusercontent.com/1484241/191708924-55e474f8-84ec-4ec7-8971-0d5c091aeed8.gif)

**Comment by hamed-musallam** [comment]
@lpatiny 

In the current implementation,  we have phase correction and absolute filters which are different filters, and because you apply the Absolute filter first then it will not meet this condition because these flags below in the code already changed.

this raises some questions:

1- Is phase correction should replace the absolute filter when applying it (they are one)?
2- if not, do you want to look if the previous filter is Absolute then skip this condition.



https://github.com/cheminfo/nmrium/blob/786b9ced87f301b2c6e1c3938022ca4502219eb4/src/data/data1d/filter1d/phaseCorrection.ts#L27
