### ISSUE TITLE
timeout wrror after only 2 seconds

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#1820]
We are receiving this error while viewing a spectrum, I think 2 seconds is too little time

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/82588017/196290686-5e5a170e-d671-440c-a8b9-5d9f2518ae1c.png">

**Comment by hamed-musallam** [comment]
@NRayya 

Please can you upload the spectra that use here so we can test them from our end?

**Comment by NRayya** [comment]
https://cloud.uni-jena.de/s/qDJgpWnHDgGNTep 
it is number 15 in the folder

**Comment by lpatiny** [comment]
This error should be catch and just display a warning. It is not an exception. @hamed-musallam could you implement this ?

**Comment by hamed-musallam** [comment]
fixed by 55617e2f8ea17d6ee36d80a7d340584d45f6692e

**Comment by targos** [comment]
@hamed-musallam We have decided to revert https://github.com/cheminfo/nmrium/commit/55617e2f8ea17d6ee36d80a7d340584d45f6692e for several reasons related to the implementation:
- The fix displayed a warning but unlike what the message says, it didn't "show only the first contour lines". To be able to do that, we would need `ml-conrec` to give an incomplete result instead of throwing (https://github.com/mljs/conrec/issues/12)
- Reducers must never have side-effects (calling `reportError` is a side-effect). They should only be responsible for creating the new state based on the dispatched action. Computing the contours (like for example loading the data from URL) should be done before the reducer is called, in a place where you can emit the alert normally. The implementation you did is very hacky and difficult to follow (imagine someone reading the `useEffect` call in the alert provider. There is no way to understand why we listen to the global 'error' event on the window).

I would recommend that you spend some time reading the new React documentation site: https://beta.reactjs.org/ (especially the parts about "Escape Hatches").
