### ISSUE TITLE
In general, the spectra editor requires many clicks. I have to select peaks, integrals, and ranges each separately. For comparison, in acd labs, the multiplet option does all the operations at once.

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1839]

**Comment by lpatiny** [comment]
Actually the 'ranges' picking is enough. Integral and peak picking are useless but are there because some people ask for it.

But range picking will take integration and multiplet analysis so it is the way to go.

**Comment by targos** [comment]
Then we should probably remove integral and peak picking from the default workspace.

**Comment by lpatiny** [comment]
Indeed the workspace was designed to solve this issue and we should decide what is the default tools. We had a bad feedback when we removed the peak picking tool and integral tool because normal users are expecting those tools.

But thinking about a new workspace (or replacing an existing one) that would be the default workspace for nmrXiv makes sense.

@hamed-musallam Please create a workspace called `Assignment`. This workspace will have all the features of the 'Default workspace' but the 'integral' and 'peak picking'.

This would be the default workspace for nmrXiv project and we will see the feedback for it. Probably we will need to improve the userguide about it.

Also please rename the 'tool tip'

![image](https://user-images.githubusercontent.com/1484241/198287723-f9721d55-2c4d-4e89-9c5c-fe49ab1caafd.png)

`Range picking and multiplet analysis`
