### ISSUE TITLE
Multiple spectra analysis and store protocol

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1873]
In multiple spectra analysis we can define zones.

@hamed-musallam Currently where are those zones stored ?

I'm wondering if this should be in the preferences part and stored in a workspace but this is to be discussed.

**Comment by hamed-musallam** [comment]
it is stored in the main state ```spectraAnalysis``` object 
https://github.com/cheminfo/nmrium/blob/d72a1a195832a3bcb713afd79cc5185d09a34676/src/component/reducer/Reducer.ts#L341

**Comment by lpatiny** [comment]
Ok thanks. After thinking about the issue I think than rather that storing protocols we will start with a database from the database panel in order to create the integration zones. I close this issue for now.

**Comment by lpatiny** [comment]
Storing in the database should not be the only possibility and the multiple integration zones should be saved in current preference workspace and stored locally. This will allow to generate many workspace for specific analysis by defining those ranges.

**Comment by hamed-musallam** [comment]
@lpatiny 

This needs further discussion because we have to take care of these points before we proceed and work on this issue

1-saving these data in the local storage and under a workspace object is risky because any future changes on the object structures or workspaces preferences that we store in ```nmr-general-settings``` will reset the data which means losing spectra analysis data unless we store it under a different key in the local storage, for example ```nmr-spectra-analysis```.


2- we have to change the local state to store only the columns and not the rows data because we will get it from the local storage. on the other than this raise a question about the single truth of data

**Comment by hamed-musallam** [comment]
closed by #2003  https://github.com/cheminfo/nmrium/pull/2003/commits/9f09e4b821d6642934961b7553a9b77262c844c9
