### ISSUE TITLE
Exclusion zones crash on coffee dataset

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1891]
![2022-11-10 04 55 12](https://user-images.githubusercontent.com/1484241/201059654-be174880-4110-470f-9399-5b2c6d55780d.gif)

@hamed-musallam could you also add a testcase so that is does not happens again.

**Comment by hamed-musallam** [comment]
@lpatiny 

the problem is because the isComplex object is always false for the coffee example, do you think the problem is in the sample itself or it is a problem in the parser?

https://github.com/cheminfo/nmrium/blob/9f90f1354b5f4a9d03b503f0ecea75144bd483d6/src/data/data1d/filter1d/exclusionZones.ts#L25

**Comment by lpatiny** [comment]
I'm wondering why the exclusion zones need complex data. If it is not complex we can just cut the real data.

**Comment by hamed-musallam** [comment]
@lpatiny 

yes you are right we only cut the real data and does not make sense to cut the imaginary data too

**Comment by lpatiny** [comment]
Even we can cut both parts if they exists it should work in both cases (with im or without im)
