### ISSUE TITLE
Hide FID spectrum when FT is available

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#2063]
We have received a feature request from chemists to hide all FIDs spectra by default  (in the spectra table) when the FT is available as the FID will be of no interest.

**Comment by hamed-musallam** [comment]
@NRayya 

in the current version of NMRium we have new preferences in the general settings and from there you can only select to load only the FT spectra and uncheck the other options

![image](https://user-images.githubusercontent.com/35760236/212059161-d7e49904-36f8-41f1-a396-e9f63470b0ce.png)

**Comment by lpatiny** [comment]
The issue here is that sometimes we have FID, sometimes FT and sometimes both and it is difficult to change between each time.

We should rather add a radio button with 3 options: In case both FT and FID are available:
- Keep both
- Keep only FT
- Keep only FID

The default could be 'Keep only FT' (this could evolve when we have an automatic processing feature9.

This is also related to:
- https://github.com/cheminfo/nmrium/issues/2005

**Comment by lpatiny** [comment]
@jobo322 Any idea about a property name ? We should start by adding this is brukerconverter.

**Comment by jobo322** [comment]
I think the idea is to prioritize the FT data over FID but it is not exclusive, I mean if for a particular folder with expnos 20, 21 for 20 there is FT data but 21 only FID. So the expected behavior is keep only FT data for 20 and the FID for 21. is it @NRayya ?

**Comment by NRayya** [comment]
@jobo322 yes exactly, as long as the user can still activate displaying all the FIDs whenever they want.

**Comment by jobo322** [comment]
it is done by c1dbe93b743c32673fe9b239e88d52f88d0bd142
