### ISSUE TITLE
Some information are confuse

### ISSUE THREAD

**Issue by baolanlequang** [cheminfo/nmrium#2226]
Can you explain why integral values are 100-based instead of 1-based? 

![Screenshot from 2023-03-07 11-44-43](https://user-images.githubusercontent.com/9006482/223401286-4d876380-c349-4324-8293-7fc89511bfe6.png)

And why this case has the NaN value?

Could you provide the document that has more details about these values?

I attached the file that I used.
Thanks.

[File012 (3).zip](https://github.com/cheminfo/nmrium/files/10908514/File012.3.zip)

**Comment by lpatiny** [comment]
This problem should be fixed in the next release. You can test it on https://dev.nmrium.org

![image](https://user-images.githubusercontent.com/1484241/223476726-25c48099-70a3-4c66-9d23-a0643cb5979c.png)

We set the 100 arbitrary value to avoid to many decimals. You can change the sum by clicking on the sum icon (or drag / drop a molfile).
