### ISSUE TITLE
Possibility to hide columns

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2598]
We would need more settings to be able to hide all (or nearly columns).

In peaks:
- kind is missing
- toolbar (delete + edit)

In Integrals:
- integral number
- from (+ allow formatting)
- to (+ allow formatting)
- toolbar (delete)

In ranges:
- range number
- rel H
- multiplicity
- assignment columns (both at once)
- toolbar

In zones:
- Currently no options and we should be able to hide everything

**Comment by hamed-musallam** [comment]
> In peaks:

> kind is missing

It is not missing, we have additional options once we want to change the kind so we did not add a dropdown list in the table and instead of that  we set the edition into a modal 
![Screenshot 2023-09-04 at 13 11 59](https://github.com/cheminfo/nmrium/assets/35760236/c309844a-7faf-4e7f-b21f-7b4f5bcd22ac)

> toolbar (delete + edit)

Do you need to hide them separately or `hideToolbar` is enough?

In Integrals:

> integral number
Do you mean hide/show the sequence number?
![Screenshot 2023-09-04 at 13 11 59](https://github.com/cheminfo/nmrium/assets/35760236/b4396a80-27eb-47f8-8066-989694441923)

> from (+ allow formatting)
>to (+ allow formatting)

>toolbar (delete)

On options `hideToolbar`, or we should be precise 'hideDelete'?

In ranges:

>range number

Is it the sequence number?

> rel H
We already have an option to control it, take a look here
![Screenshot 2023-09-04 at 13 11 59](https://github.com/cheminfo/nmrium/assets/35760236/ad1f5ffb-0641-4af3-ab4b-f1c1b6a30218)
