### ISSUE TITLE
No projection shown if both Bruker and JCAMP 1D present

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#2750]
If a zipped dataset contains both Bruker and JCAMP 1D spectra, the 2D spectra will have no projections even if all but one 1D spectra are hidden.

Examples:
[cyclopentanon_120-92-3.zip](https://github.com/cheminfo/nmrium/files/13335150/cyclopentanon_120-92-3.zip)
[2-picolin_109-06-8a.zip](https://github.com/cheminfo/nmrium/files/13335153/2-picolin_109-06-8a.zip)

Remove either the Bruker or JCAMP 1D and it works again.

@evaziegler

**Comment by hamed-musallam** [comment]
initially, in accordance with the default configuration, we prioritize loading the FT spectrum over the FID spectrum when both are available in the same file. However, due to the presence of multiple proton spectra and likewise, for carbon, we haven't specified which spectrum will be utilized for projection in 2D by default so in this case the user should select which proton or carbon for the projection.

Do you have any suggestions?

**Comment by lpatiny** [comment]
Yes in order to display the trace there should be either only one 1D or there should be one selected 1D (if there are many).

I agree that we often have this issue and this is not intuitive. We could do that if there is more than one 1D spectrum and there is none selected by default we will take the first one.

**Comment by hamed-musallam** [comment]
i'm not sure, is this general rule, or just if we have 2d samples

**Comment by lpatiny** [comment]
Just to clarify if no 1D spectrum is selected, we will not select one but only display the first in the list as the 2D trace.

**Comment by jliermann** [comment]
Thanks for your comments, this is actually two issues, a) that is not intuitive for the user and b) that there is a bug as described by me above.
Do I understand correctly that @hamed-musallam fixed the bug in PR #2770? :-)

**Comment by hamed-musallam** [comment]
@jliermann 

yes, it is fixed, could you test with https://dev.nmrium.org/

**Comment by hamed-musallam** [comment]
fixed in https://github.com/cheminfo/nmrium/pull/2770
