### ISSUE TITLE
Unhandled error when picking a very small range

### ISSUE THREAD

**Issue by targos** [cheminfo/nmrium#3016]
Zoom in enough and use shift+draw with the range picking tool:

https://github.com/cheminfo/nmrium/assets/2352663/e5b60bda-5441-4dcc-a316-b25f856db85e

**Comment by lpatiny** [comment]
It does not really make sense to draw such a small range because the integration will never be valid anyway. However it should not throw an error neither.
The same error will happens when we resize a range and it is too small as well.
@jobo322 please improve the range detection algorithm so that we don't try SG in case we don't have enough points. Practically I think we can only give from / to ? Should we also take the highest point ?

**Comment by hamed-musallam** [comment]
I can think of different approaches, but I believe it's best to define the logger globally for universal access and each NMRium instance can have its own context for filtering the loggers.

**Comment by targos** [comment]
Just keep in mind that currently this function is called from a reducer, which is not allowed to have side-effects (modifying a global state is a side-effect)

**Comment by targos** [comment]
In general, algorithms should be applied before calling the reducer to avoid this kind of problems.

**Comment by hamed-musallam** [comment]
Yes, in this scenario, we can lift the function up and directly call it in the callback
