### ISSUE TITLE
Bug with prediction and expanded protons

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#3229]
If you predict ethylbenzene and check the COSY.

The hover correctly highlight the corresponding atoms (carbon).

But if you expand the hydrogens (shift + click on the atom) the highlight does not work anymore, even if you collapse again.

![2024-09-11 10 12 56](https://github.com/user-attachments/assets/aaa2ad6e-1f16-4294-8c89-3b6aeafa681f)

@hamed-musallam Could you have a look at this bug. It could be on my side in react-ocl-nmr

**Comment by hamed-musallam** [comment]
@lpatiny 
it appears that due to changes in the rendering and positioning of the molecule structure in the OLCnmr component, the setHoverAtom function is no longer being triggered (Due to the event attached), which causes the hover effect on 2D signals to persist. As a temporary workaround, we can call the function responsible for handling the mouse leave action when Shift + Click is used to resolve this issue.
