### ISSUE TITLE
Compress NMRIUM json data for download / upload

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#950]
The standalone NMRIUM files generated become very big. A lot of space could be saved if they are offered for download in compressed form (e. g., ZIP) and if the upload also accepted them in compressed form. For users with low upstream bandwidth, this would save a lot of time.

**Comment by lpatiny** [comment]
@hamed-musallam 

By default when we are saving a .nmrium file we can:
- JSON.stringify without spaces !
- zip the .nmrium file using jszip but while keeping the .nmrium extension.

This would be the default behaviour with CTRL + S

If we press SHIFT + CTRL + S we would save the current file (hidden feature we need to document).

When loading the file we need to check the 4 first bytes of the buffer so see if it matches: hexadecimal code `50 4b 03 04` (file signature, https://en.wikipedia.org/wiki/List_of_file_signatures)

If it is zipped we unzip and load otherwise we load directly. Like that we don't need to add one more extension.
